#range is function....
#in membership operator...
#range is overloaded function.... 
#range with 1 param range(10) #ending condition.... 0 to 10 and 10 will be excluded...
#range with 2 param range(1,11) #1 is starting point.. 11 is ending point and 11 will be exc...
#range with 3 param range(1,20,2) starting with 1 ending to 20 and increment by 2...
# for i in range(1,21,1):
#     print(i)

for i in range(10,0,-1):
    print(i)
    #
    #
    #
    
    